server:
  port: 10002
  servlet:
    context-path: /

spring:
  application:
    name: micr-web
  mvc:
    #解决springboot2.6.2使用swagger的问题
    pathmatch:
      matching-strategy: ant_path_matcher

dubbo:
  application:
    name: micr-web
  registry:
    id: zk-registry
    address: zookeeper://192.168.11.111:2181
    timeout: 60000
